config/routes.rb
NaganoComfortInn::Application.routes.draw do
  # default_url_options :host => "localhost:3000"
  root to: 'pages#home'
  post "results", to:'pages#results'
  post "confirmation", to:'pages#confirmation'
  post "confirmed", to:'pages#confirmed'
  post 'search', to:'admin/reservations#search'

  namespace :admin do
    resources :room_types
    resources :views
    resources :change_prices, only: [:index]
    resources :rooms
    resources :customers
    resources :reservations
    resources :by_day_of_week_prices
    resources :by_time_of_year_prices
    resources :invoices
    resources :reports
    resources :room_services
  end
end

app/controllers/admin/change_prices_controller.rb
module Admin
  class ChangePricesController < ApplicationController
    def index
      @views = View.not_deleted
      @room_types = RoomType.not_deleted
      @by_time_of_year_prices = ByTimeOfYearPrice.not_deleted
      @by_day_of_week_prices = ByDayOfWeekPrice.not_deleted
    end
  end
end

app/views/admin/change_prices/index.haml
%h2 Prix en fonction de la vue
%table.table
  %thead.thead-dark
    %tr
      %th Vue
      %th Variation du prix
      %th Prix fixe
      %th{:colspan => "3"} Actions
  %tbody
    - @views.each do |view|
      %tr
        %td= view.view_desc
        %td= view.view_percent_variation
        %td= number_with_precision(view.view_fixed_price, precision: 2)
        %td= button_to 'Voir', admin_view_path(view), :method => :get, class: "btn btn-outline-primary"
        %td= button_to 'Modifier', edit_admin_view_path(view), :method => :get, class: "btn btn-outline-info"
        %td= button_to 'Supprimer', admin_view_path(view), method: :delete, class: "btn btn-outline-danger"
%p
  = link_to 'Entrer une nouvelle vue', new_admin_view_path

%h2 Prix en fonction du type de chambre
%table.table
  %thead.thead-dark
    %tr
      %th Type
      %th Variation du prix
      %th Prix fixe
      %th{:colspan => "3"} Actions
  %tbody
    - @room_types.each do |room_type|
      %tr
        %td= room_type.type_desc
        %td= room_type.type_percent_variation
        %td= number_with_precision(room_type.type_fixed_price, precision: 2)
        %td= button_to 'Voir', admin_room_type_path(room_type), :method => :get, class: "btn btn-outline-primary"
        %td= button_to 'Modifier', edit_admin_room_type_path(room_type), :method => :get, class: "btn btn-outline-info"
        %td= button_to 'Supprimer', admin_room_type_path(room_type), method: :delete, class: "btn btn-outline-danger"
%p
  = link_to 'Entrer un nouveau type de chambre', new_admin_room_type_path

%h2 Prix en fonction du jour de la semaine
%table.table
  %thead.thead-dark
    %tr
      %th Description
      %th Variation du prix
      %th Prix fixe
      %th{:colspan => "3"} Actions
  %tbody
    - @by_day_of_week_prices.each do |day|
      %tr
        %td= day.day_desc
        %td= day.percent_variation
        %td= number_with_precision(day.fixed_price_variation, precision: 2)
        %td= button_to 'Voir', admin_by_day_of_week_price_path(day), :method => :get, class: "btn btn-outline-primary"
        %td= button_to 'Modifier', edit_admin_by_day_of_week_price_path(day), :method => :get, class: "btn btn-outline-info"
        %td= button_to 'Supprimer', admin_by_day_of_week_price_path(day), method: :delete, class: "btn btn-outline-danger"
%p
  = link_to 'Entrer un nouveau prix', new_admin_by_day_of_week_price_path

%h2 Prix en fonction de la période
%table.table
  %thead.thead-dark
    %tr
      %th Description
      %th Variation du prix
      %th Prix fixe
      %th{:colspan => "3"} Actions
  %tbody
    - @by_time_of_year_prices.each do |time|
      %tr
        %td= time.time_desc
        %td= time.percent_variation
        %td= number_with_precision(time.fixed_price_variation, precision: 2)
        %td= button_to 'Voir', admin_by_time_of_year_price_path(time), :method => :get, class: "btn btn-outline-primary"
        %td= button_to 'Modifier', edit_admin_by_time_of_year_price_path(time), :method => :get, class: "btn btn-outline-info"
        %td= button_to 'Supprimer', admin_by_time_of_year_price_path(time), method: :delete, class: "btn btn-outline-danger"
%p
  = link_to 'Entrer un nouveau prix', new_admin_by_time_of_year_price_path