config/routes.rb
NaganoComfortInn::Application.routes.draw do
  # default_url_options :host => "localhost:3000"
  root to: 'pages#home'
  post "results", to:'pages#results'
  post "confirmation", to:'pages#confirmation'
  post "confirmed", to:'pages#confirmed'
  post 'search', to:'admin/reservations#search'

  namespace :admin do
    resources :room_types
    resources :views
    resources :change_prices, only: [:index]
    resources :rooms
    resources :customers
    resources :reservations
    resources :by_day_of_week_prices
    resources :by_time_of_year_prices
    resources :invoices
    resources :reports
    resources :room_services
  end
end

app/models/reservation.rb
require 'date'
class Reservation < ActiveRecord::Base
  attr_accessible :customer_id, :start_date, :end_date, :special_request, :is_online_reservation
  has_many :reservations_rooms
  has_many :rooms, through: :reservations_rooms
  has_many :invoices
  belongs_to :customer
  accepts_nested_attributes_for :rooms

  scope :not_deleted, -> { where(deleted_at: nil) }

  validates :start_date, presence: { strict: true }, if: -> {:start_date.to_s >= Date.today.strftime("%Y-%m-%d")}
  validates :end_date, presence: { strict: true }, if: -> {:end_date.to_s > Date.today.strftime("%Y-%m-%d")}
  validates :customer, presence: { strict: true }
end

app/controllers/admin/reservations_controller.rb
require 'date'
module Admin
  class ReservationsController < ApplicationController
    def show
      @reservation = Reservation.find(params[:id])
    end

    def index
      @reservations = Reservation.not_deleted
      @invoices = Invoice.not_deleted
    end

    def edit
      @reservation = Reservation.find(params[:id])
      @customers = Customer.not_deleted
      @rooms = Room.not_deleted
    end

    def update
      @reservation = Reservation.find(params[:id])
      @reservation.update_attributes(params[:reservation])
      @reservations_room = ReservationsRoom.find(params[:room_id])
      redirect_to admin_reservation_path(@reservation)
    end

    def destroy
      @reservation = Reservation.find(params[:id])
      @reservation.update_column(:deleted_at, Date.today.to_formatted_s(:db))
      redirect_to admin_reservations_path
    end

    def search
      @rooms = Room.not_deleted
    end
  end
end

app/views/admin/reservations/edit.haml
%div.jumbotron
  %h1.display-4 Modifier une réservation
  = form_for(@reservation, url: admin_reservation_path) do |f|
    %p
      = f.label :customer_id
      %br/
      = f.select :customer_id, options_for_select(@customers.map{|c| [c.first_name + " " + c.last_name, c.id]}, @reservation.customer_id)
    //%p
    // = f.label :room_id
    // %br/
    //= f.select :room_id, options_for_select(@rooms.map{|r| [r.number, r.id]}, @reservation.room_id)

    %p
      = f.submit
      %br/
  = link_to 'Retour', admin_reservations_path

app/views/admin/reservations/index.haml
%h2 Liste des réservations
%table.table
  %thead.thead-dark
    %tr
      %th Numéro de réservation
      %th Nom du client
      %th{:colspan => "3"} Actions
  %tbody
    - @reservations.each do |reservation|
      %tr
        %td= reservation.id
        %td= reservation.customer.first_name + " " + reservation.customer.last_name
        %td= button_to 'Voir', admin_reservation_path(reservation), :method => :get, class: "btn btn-outline-primary"
        %td= button_to 'Modifier', edit_admin_reservation_path(reservation), :method => :get, class: "btn btn-outline-info"
        %td= button_to 'Supprimer', admin_reservation_path(reservation), method: :delete, class: "btn btn-outline-danger"
%p
  = link_to 'Nouvelle recherche', search_path

%h2 Liste des factures
%table.table
  %thead.thead-dark
    %tr
      %th Numéro de facture
      %th Nom du client
      %th Numéro de réservation
      %th{:colspan => "3"} Actions
  %tbody
    - @invoices.each do |invoice|
      %tr
        %td= invoice.id
        %td= invoice.customer.first_name + " " + invoice.customer.last_name
        %td= invoice.reservation_id
        %td= button_to 'Voir', admin_invoice_path(invoice), :method => :get, class: "btn btn-outline-primary"
        %td= button_to 'Modifier', edit_admin_invoice_path(invoice), :method => :get, class: "btn btn-outline-info"
        %td= button_to 'Supprimer', admin_invoice_path(invoice), method: :delete, class: "btn btn-outline-danger"
%p
  = link_to 'Nouvelle facture', new_admin_invoice_path

app/views/admin/reservations/search.haml
%div.jumbotron
  %h1.display-4 Recherche par date
  = form_for :res, method: 'post', url: results_path do |f|
    %p
      = f.label :start_date, "Arrivée"
      %br/
      = f.text_field :start_date, class: 'datepicker'
    %p
      = f.label :end_date, "Départ"
      %br/
      = f.text_field :end_date, class: 'datepicker'
    %p
      = f.submit "Rechercher"
      %br/
  = link_to 'Retour', admin_reservations_path

app/views/admin/reservations/show.haml
%div.jumbotron
  %h1.display-4 Détails
  %p
    Nom du client: #{@reservation.customer.first_name.to_s + " " + @reservation.customer.last_name}

  %p
    Chambres réservées:
    - @reservation.reservations_rooms.each do |r|
      = r.room.number.to_s + "; "

  %p
    = link_to 'Retour', admin_reservations_path