config/routes.rb
NaganoComfortInn::Application.routes.draw do
  # default_url_options :host => "localhost:3000"
  root to: 'pages#home'
  post "results", to:'pages#results'
  post "confirmation", to:'pages#confirmation'
  post "confirmed", to:'pages#confirmed'
  post 'search', to:'admin/reservations#search'

  namespace :admin do
    resources :room_types
    resources :views
    resources :change_prices, only: [:index]
    resources :rooms
    resources :customers
    resources :reservations
    resources :by_day_of_week_prices
    resources :by_time_of_year_prices
    resources :invoices
    resources :reports
    resources :room_services
  end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :phone, :email, :credit_card_num
  has_many :reservations
  has_many :invoices

  scope :not_deleted, -> { where(deleted_at: nil) }

  @VALID_EMAIL_REGEX = /^.+@.+$/

  validates :first_name, presence: { strict: true }
  validates :last_name, presence: { strict: true }
  validates :phone, presence: { strict: true }, :length => { :minimum => 10, :maximum => 15 }
  validates :email, format: { with: @VALID_EMAIL_REGEX, uniqueness: { case_sensitive: false, scope: :not_deleted}, length: { minimum: 4, maximum: 254 }, strict: true}
  validates :credit_card_num, numericality: { strict: true }, :length => { :minimum => 16, :maximum => 16, strict: true }
end

app/controllers/admin/customers_controller.rb
# encoding: UTF-8
module Admin
  class CustomersController < ApplicationController
    def show
      @customer = Customer.find(params[:id])
    end

    def index
      @customers = Customer.not_deleted
    end

    def new
      respond_to do |format|
        format.html { redirect_to admin_customers_url }
        format.json
        format.js { render layout: false }
      end
    end

    def edit
      @customer = Customer.find(params[:id])
    end

    def create
      @customer = Customer.new(params[:customer])
      if params[:customer][:first_name].present? && params[:customer][:last_name].present? &&
        params[:customer][:email].present? && params[:customer][:credit_card_num].present? &&
        params[:customer][:phone].present?
        @customer.save
        flash.now[:success] = "Client enregistré avec succès!"
      else
        flash.now[:danger] = "Vérifiez la conformité de chaque champ."
      end

      # render 'admin/customers/create.js.erb', layout: false
      respond_to do |format|
        format.html { redirect_to admin_customers_url }
        format.json
        format.js { render layout: false }
      end
    end

    def update
      @customer = Customer.find(params[:id])
      @customer.update_attributes(params[:customer])
      redirect_to admin_customer_path(@customer)
    end

    def destroy
      @customer = Customer.find(params[:id])
      @customer.update_column(:deleted_at, Date.today.to_formatted_s(:db))
      respond_to do |format|
        format.html { redirect_to admin_customers_url }
        format.json
        format.js { render layout: false }
      end
    end
  end
end

app/views/admin/customers/_customer.haml
%tr{class: "customer_id_#{customer.id}"}
  %td= customer.first_name
  %td= customer.last_name
  %td= customer.phone
  %td= customer.email
  %td= button_to 'Voir', admin_customer_path(customer), class: "btn btn-outline-primary", :method => :get, class: "btn btn-outline-primary"
  %td= button_to 'Modifier', edit_admin_customer_path(customer), class: "btn btn-outline-info", :method => :get
  %td= button_to 'Supprimer', admin_customer_path(customer), method: :delete, remote: true, class: "btn btn-outline-danger"

app/views/admin/customers/_form.haml
%div.jumbotron
  %h1.display-4 Nouveau client
  %div#newForm
    = form_for(:customer, url: admin_customers_url, remote: true) do |f|
      %p
        = f.label :first_name, "Prénom"
        %br/
        = f.text_field :first_name
      %p
        = f.label :last_name, "Nom"
        %br/
        = f.text_field :last_name
      %p
        = f.label :phone, "Téléphone"
        %br/
        = f.text_field :phone
      %p
        = f.label :email, "Courriel"
        %br/
        = f.text_field :email
      %p
        = f.label :credit_card_num, "Numéro de carte de crédit"
        %br/
        = f.text_field :credit_card_num
      %p
        = f.submit
        %br/

app/views/admin/customers/create.js.erb
<% if @customer.persisted? %>
  $('#newCustomer').remove();
  $('#newCustomerLink').show();
  $('#customersBody').append("<%= j render @customer %>")
<% end %>
$("#flash").html("<%= j render 'layouts/flash_messages' %>");

app/views/admin/customers/destroy.js.erb
<% if @customer.deleted_at? %>
  //document.querySelector('#deletion_msg').fadeIn();
  let node = document.createElement("li");
  let textnode = document.createTextNode("Client supprimé!");
  node.appendChild(textnode);
  document.querySelector('#deletion_msg').appendChild(node);

  let customer_id = '<%= @customer.id %>';
    $('.customer_id_' + customer_id).fadeOut();

  //FadeOut
  let fadeTarget = document.querySelector("#deletion_msg").lastChild
  let val = 1;
  let time = setInterval(function () {
      if (val > 0) {
          val -= 0.05;
          fadeTarget.style.opacity = String(val);
      }
      else {
          clearInterval(time);
      }
  }, 50);

  setTimeout(()=>{
      let list = document.querySelector("#deletion_msg");
      list.removeChild(list.childNodes[0]);
  }, 1500)

<% end %>

app/views/admin/customers/edit.haml
%div.jumbotron
  %h1.display-4 Modification d'un client
  = form_for(@customer, url: admin_customer_path) do |f|
    %p
      = f.label :first_name
      %br/
      = f.text_field :first_name
    %p
      = f.label :last_name
      %br/
      = f.text_field :last_name
    %p
      = f.label :email
      %br/
      = f.text_field :email
    %p
      = f.submit
      %br/
  %p
    = link_to 'Retour', admin_customers_path

app/views/admin/customers/index.haml
%div#errors
%h2 Liste des clients
%table.table
  %thead.thead-dark
    %tr
      %th Prénom
      %th Nom
      %th Téléphone
      %th Courriel
      %th{:colspan => "3"} Actions
  %tbody#customersBody
    =render @customers
%div#newCustomer
%div#newCustomerLink
  = link_to 'Inscrire un nouveau client', new_admin_customer_path, remote: true
%ul#deletion_msg

app/views/admin/customers/new.haml
%div.jumbotron
  %h1.display-4 Inscription d'un nouveau client
  = form_for :customer, url: admin_customers_path do |f|
    %p
      = f.label :first_name
      %br/
      = f.text_field :first_name
    %p
      = f.label :last_name
      %br/
      = f.text_field :last_name
    %p
      = f.submit
      %br/
  = link_to 'Retour', admin_customers_path

app/views/admin/customers/new.js.erb
$('#newCustomer').html("<%= j render 'form', customer: @customer %>");
$('#newCustomerLink').hide();

app/views/admin/customers/show.haml
%div.jumbotron
  %h1.display-4 Détails
  %p
    Prénom: #{@customer.first_name}
  %p
    Nom: #{@customer.last_name}
  %p
    Téléphone: #{@customer.phone}
  %p
    Courriel: #{@customer.email}
  %p
    Numéro de carte de crédit: #{@customer.credit_card_num}
  %p
    = link_to 'Retour', admin_customers_path