config/routes.rb
NaganoComfortInn::Application.routes.draw do
  # default_url_options :host => "localhost:3000"
  root to: 'pages#home'
  post "results", to:'pages#results'
  post "confirmation", to:'pages#confirmation'
  post "confirmed", to:'pages#confirmed'
  post 'search', to:'admin/reservations#search'

  namespace :admin do
    resources :room_types
    resources :views
    resources :change_prices, only: [:index]
    resources :rooms
    resources :customers
    resources :reservations
    resources :by_day_of_week_prices
    resources :by_time_of_year_prices
    resources :invoices
    resources :reports
    resources :room_services
  end
end

app/views/layouts/_flash_messages.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name} "}
    = msg

app/views/layouts/_footer.haml
%footer#sticky-footer.py-4.text-white-50
  .container.text-center
    %small Nagano Comfort Inn  © Par Carl Genest
:javascript
  $(".datepicker").datepicker({ dateFormat: 'yy-mm-dd' });

app/views/layouts/_header.haml
%nav#navbar.navbar.navbar-expand-lg.navbar-dark
  = link_to image_tag('nagano-logo.jpg'), root_path, class: "navbar-brand"
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item.dropdown
        %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
          Espace Client
        .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
          %a.dropdown-item{:href => "#"} Réserver une chambre
          %a.dropdown-item{:href => "#"} Mes réservations
          .dropdown-divider
          %a.dropdown-item{:href => "#"} M'inscrire
      %li.nav-item.dropdown
        %a#navbarDropdown2.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
          Espace Gestion
        .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
          = link_to "Modifier des comptes client", admin_customers_path, class: "dropdown-item"
          = link_to "Modifier les réservations", admin_reservations_path, class: "dropdown-item"
          = link_to "Modifier les chambres", admin_rooms_path, class: "dropdown-item"
          = link_to "Modifier les prix", admin_change_prices_path, class: "dropdown-item"
          = link_to "Service aux chambres", admin_room_services_path, class: "dropdown-item"
          .dropdown-divider
          = link_to "Rapports journaliers", admin_reports_path, class: "dropdown-item"
    %form.form-inline.my-2.my-lg-0{ action: results_path, method: 'post', name: 'res' }
      %div.date-container
        %input.datepicker{"aria-label" => "Search", name: "res[start_date]", :placeholder => "Arrivée", :type => "search"}/
      %div.date-container
        %input.datepicker{"aria-label" => "Search", name: "res[end_date]", :placeholder => "Départ", :type => "search"}/
      %div.date-container
        %button.btn.btn-outline-success.my-2.my-sm-0{:type => "submit"} Rechercher

app/views/layouts/application.haml
!!!
%html
  %head
    %title NaganoComfortInn
    %link{:href => "http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/themes/redmond/jquery-ui.css", :rel => "stylesheet", :type => "text/css"}/
    %link{:crossorigin => "anonymous", :href => "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css", :integrity => "sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO", :rel => "stylesheet"}/
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body.d-flex.flex-column
    = render 'layouts/header'
    #page-content
      #flash
        = render 'layouts/flash_messages'
      = yield
    = render 'layouts/footer'
  %script{:crossorigin => "anonymous", :integrity => "sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo", :src => "https://code.jquery.com/jquery-3.3.1.slim.min.js"}
  %script{:crossorigin => "anonymous", :integrity => "sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49", :src => "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"}
  %script{:crossorigin => "anonymous", :integrity => "sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy", :src => "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"}
  %script{:src => "http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.js", :type => "text/javascript"}
  %script{:src => "http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.js", :type => "text/javascript"}